### ISSUE TITLE
how to video test?

### ISSUE THREAD

**Issue by changsubi** [MasterBin-IIAU/UNINEXT#12]
i can demo for image. but don't work for video

Traceback (most recent call last):
  File "projects/UNINEXT/demo.py", line 208, in <module>
    for vis_frame in tqdm.tqdm(demo.run_on_video(video, args.confidence_threshold), total=num_frames):
  File "/home/csyun/.local/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/csyun/Desktop/UNINEXT/projects/UNINEXT/predictor.py", line 138, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
TypeError: __call__() missing 1 required positional argument: 'task'

what is the problem?

**Comment by MasterBin-IIAU** [comment]
@changsubi Hi, for now, we do not have a complete demo script for all video-level tasks. However, you can refer to this [issue](https://github.com/MasterBin-IIAU/UNINEXT/issues/8) to find a simple tutorial about demo for MOT.

**Comment by MasterBin-IIAU** [comment]
@jiahui1688 Hi, for datasets of these tasks, such as (Ref-)Youtube-VOS and (Ref-)DAVIS, our code will save the mask results. You can check them under outputs dir. We will consider introducing more complicated demo script for supporting taking any video as the input. For MOTS, you can still refer to the instruction given in this [issue](https://github.com/MasterBin-IIAU/UNINEXT/issues/8) but you need to change a few lines of code.

**Comment by jiahui1688** [comment]
@MasterBin-IIAU  OK, I'll try to do it. Thank you!

**Comment by changsubi** [comment]
@MasterBin-IIAU Thank you

**Comment by ajdroid** [comment]
@MasterBin-IIAU, just wanted to check if video level demos (arbitrary input video) for MOT/MOTS was still something you were considering.

**Comment by beratersari** [comment]
Hi is there an update about that? It will be a pleasure if you release a demo for video segmentation. @ajdroid
