### ISSUE TITLE
Custom dataset AssertionError while testing

### ISSUE THREAD

**Issue by cristof-r** [MasterBin-IIAU/UNINEXT#18]
Thank you very much for this project, I have been trying to train your model for instance segmentation on my own dataset, which seems to work fine.
However, at the testing phase I get this error:

```
...
[03/29 22:18:34 d2.evaluation.evaluator]: Inference done 233/298. Dataloading: 0.0010 s/iter. Inference: 0.1157 s/iter. Eval: 3.6628 s/iter. Total: 3.7796 s/iter. ETA=0:04:05
[03/29 22:18:39 d2.evaluation.evaluator]: Inference done 271/298. Dataloading: 0.0010 s/iter. Inference: 0.1141 s/iter. Eval: 3.1437 s/iter. Total: 3.2588 s/iter. ETA=0:01:27
[03/29 22:18:42 d2.evaluation.evaluator]: Total inference time: 0:14:30.508410 (2.971018 s / iter per device, on 1 devices)
[03/29 22:18:42 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:33 (0.113249 s / iter per device, on 1 devices)
[03/29 22:18:43 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
ERROR [03/29 22:18:43 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "UNINEXT/detectron2/engine/train_loop.py", line 150, in train
    self.after_step()
  File "UNINEXT/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "UNINEXT/detectron2/engine/hooks.py", line 555, in after_step
    self._do_eval()
  File "UNINEXT/detectron2/engine/hooks.py", line 528, in _do_eval
    results = self._func()
  File "UNINEXT/detectron2/engine/defaults.py", line 455, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "UNINEXT/detectron2/engine/defaults.py", line 620, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "UNINEXT/detectron2/evaluation/evaluator.py", line 204, in inference_on_dataset
    results = evaluator.evaluate()
  File "UNINEXT/detectron2/evaluation/coco_evaluation.py", line 211, in evaluate
    self._eval_predictions(predictions, img_ids=img_ids)
  File "UNINEXT/detectron2/evaluation/coco_evaluation.py", line 250, in _eval_predictions
    assert category_id <= num_classes, (
AssertionError: A prediction has class=56, but the dataset only has 21 classes and predicted class id should be in [0, 20].
```

My config files looks like this:

```
_BASE_: "image_joint_r50.yaml"
MODEL:
  WEIGHTS: "weights/R-50.pkl"
DATASETS:
  TRAIN: ("coco_data_train", )
  TEST: ("coco_data_test", )
SOLVER:
  IMS_PER_BATCH: 5 
  STEPS: (5000, 10000)  
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2499
DATALOADER:
  DATASET_RATIO: [1]
  DATASET_BS: [2]
  USE_RFS: [False]
  NUM_WORKERS: 1
OUTPUT_DIR: outputs/single_task_det
```
which is based on: [single_task_det.yaml](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/configs/single_task_det.yaml)

I add my COCO dataset the same as described in [objects365_v2.py](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/uninext/data/objects365_v2.py), with the only difference that the range only goes upto 21 according the the number of classes im my dataset:

`thing_dataset_id_to_contiguous_id = {i + 1: i for i in range(21)}`

How I register my coco data:

```
register_coco_instances(
  "coco_data_train",
  _get_builtin_metadata(),
  PATH_DATA + "coco_train_data.json",
  PATH_DATA + "train/",
)

register_coco_instances(
  "coco_data_test",
  _get_builtin_metadata(),
  PATH_DATA + "coco_test_data.json",
  PATH_DATA + "test/",
)
```

I would appreciate any help very much.

**Comment by MasterBin-IIAU** [comment]
@cristof-r Hi, after replacing coco with your own dataset, you also need to replace COCO_CATEGORIES with your own categories in [line 156](https://github.com/MasterBin-IIAU/UNINEXT/blob/7aba5c1c9a95276588eceaab119988b9ec893c59/projects/UNINEXT/uninext/data/coco_dataset_mapper_uni.py#L156). You can refer to [line 18](https://github.com/MasterBin-IIAU/UNINEXT/blob/7aba5c1c9a95276588eceaab119988b9ec893c59/projects/UNINEXT/uninext/data/coco_dataset_mapper_uni.py#L18) to obtain your own categories.

**Comment by cristof-r** [comment]
Thank you very much, it works perfectly now! 
Another question, what would be the best way to benchmark the inference speed of your model?

**Comment by MasterBin-IIAU** [comment]
Hi, we haven't formally do this for UNINEXT before. However, when you infer UNINEXT on datasets such as COCO, the printed log will show the related statistics.

**Comment by cristof-r** [comment]
Thanks a lot!
