### ISSUE TITLE
bug : AttributeError: DO_LN

### ISSUE THREAD

**Issue by wokaikaixinxin** [MasterBin-IIAU/UNINEXT#22]
In image_joint_r50.yaml, if set `USE_DINO: False`, there will be a bug:
`Traceback (most recent call last):
  File "/root/UNINEXT/projects/UNINEXT/train_net.py", line 247, in <module>
    args=(args,),
  File "/root/UNINEXT/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/root/UNINEXT/projects/UNINEXT/train_net.py", line 225, in main
    trainer = Trainer(cfg)
  File "/root/UNINEXT/detectron2/engine/defaults.py", line 376, in __init__
    model = self.build_model(cfg)
  File "/root/UNINEXT/detectron2/engine/defaults.py", line 517, in build_model
    model = build_model(cfg)
  File "/root/UNINEXT/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/root/UNINEXT/projects/UNINEXT/uninext/uninext_img.py", line 113, in __init__
    cfg=cfg)
  File "/root/UNINEXT/projects/UNINEXT/uninext/models/deformable_detr/deformable_transformer.py", line 98, in __init__
    do_ln=cfg.MODEL.DO_LN
  File "/root/anaconda3/envs/yolov7/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: DO_LN

Process finished with exit code 1
`
It seems like there is no "cfg.MODEL.DO_LN". How to set "cfg.MODEL.DO_LN"?

**Comment by MasterBin-IIAU** [comment]
Hi, you can set cfg.MODEL.DO_LN=True at [config.py](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/uninext/config.py)

**Comment by wokaikaixinxin** [comment]
> Hi, you can set cfg.MODEL.DO_LN=True at [config.py](https://github.com/MasterBin-IIAU/UNINEXT/blob/master/projects/UNINEXT/uninext/config.py)

Thanks
